import { useEffect } from 'react';
import { Page, Header, Content, SupportButton } from '@backstage/core-components';
import { useApi } from '@backstage/core-plugin-api';
import { appsApiRef } from '@internal/backstage-plugin-apps';

export const VibeCodingComponent = () => {
    const appsApi = useApi(appsApiRef);

    useEffect(() => {
        const handleMessage = async (event: MessageEvent) => {
            // Security check: In production, verify event.origin

            const { preview_url, urls } = event.data;

            if (preview_url && urls) {
                console.log('Received Vibe App:', { preview_url, urls });

                // Create an app for the preview URL
                // We might want to parse the URL to get a slug or name
                // For now, let's generate a random slug or use the last part of the URL

                try {
                    const slug = `vibe-${Math.random().toString(36).substring(7)}`;
                    await appsApi.createApp({
                        slug,
                        name: `Vibe App ${slug}`,
                        embed_url: preview_url,
                        description: 'Generated by Vibe Coding',
                        released: new Date().toISOString(),
                        user_uri: 'spacify:user:drsounds', // Default user
                        vendor_uri: 'spacify:vendor:spacify',
                        tags: ['vibe', 'generated'],
                        icon_url: '',
                        header_image_url: '',
                        category_uri: 'spacify:category:utility',
                        website_url: preview_url
                    });
                    alert(`Created app: ${slug}`);
                } catch (e) {
                    console.error('Failed to create app:', e);
                    alert('Failed to create app');
                }
            }
        };

        window.addEventListener('message', handleMessage);
        return () => window.removeEventListener('message', handleMessage);
    }, [appsApi]);

    return (
        <Page themeId="tool">
            <Header title="Vibe Coding" subtitle="Generate apps with AI">
                <SupportButton>This tool allows you to generate apps using Vibe Coding.</SupportButton>
            </Header>
            <Content noPadding>
                <iframe
                    src="http://localhost:4000"
                    style={{
                        width: '100%',
                        height: '100%',
                        border: 'none',
                        display: 'block',
                    }}
                    title="Vibe Coding"
                />
            </Content>
        </Page>
    );
};
